version: "3"
services:

  application1:
    build: ./Docker/ApachePHP7
    ports :
     - "8070:80"
    volumes:
     - ./Application1/:/var/www/html/
    links:
     - database

  application2:
      build: ./Docker/ApachePHP5
      ports :
       - "8080:80"
      volumes:
       - ./Application2/:/var/www/html/
      links:
       - database

  phpmyadmin:
     image: phpmyadmin/phpmyadmin
     ports :
      - "8090:80"
     environment:
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
     links:
      - database:db

  database:
    image: mysql:5.5
    ports:
     - "3306:3306"
    volumes:
     - ./Database:/var/lib/mysql 
    environment:
       - MYSQL_ROOT_PASSWORD=root
